### ==========================================
### 🌍 ENVIRONMENT VARIABLES
### ==========================================
@baseUrl = https://internship-blog-api.onrender.com/api

# ⚠️ INSTRUCTIONS:
# 1. Run the LOGIN or REGISTER route below.
# 2. Copy the "accessToken" from the server response.
# 3. Paste it here:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmE0N2JmNWM4MTY2YTBmZmJlMTNkNiIsImlhdCI6MTc4MTE1NTkyNywiZXhwIjoxNzgxMTU2ODI3fQ.BCpPrWL7UHYWIVDjYdI197AfAa-_LQJCa0eLEIuEq1M

# 4. Run the CREATE BLOG route.
# 5. Copy the "_id" of the new blog from the server response.
# 6. Paste it here:
@blogId = 6a2a48b12fb3e09f56ab6cd8


### ==========================================
### 🔐 GROUP 1: AUTHENTICATION
### ==========================================

### 1. Register a New User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Intern Tester",
  "email": "tester@internship.com",
  "password": "securepassword123"
}

### 2. Login User (Use this to get your token!)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "tester@internship.com",
  "password": "securepassword123"
}


### ==========================================
### 🟢 GROUP 2: CREATE BLOGS
### ==========================================

### 3. SUCCESS - Create a valid blog
POST {{baseUrl}}/blogs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "My Complete API Blueprint",
  "content": "This project now handles full authentication, CRUD, and pagination.",
  "tags": ["backend", "express", "mongodb"]
}

### 4. ERROR - Zod Validation Fail (Title too short)
POST {{baseUrl}}/blogs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Hi", 
  "content": "This content is long enough, but the title is too short.",
  "tags": ["error-test"]
}

### 5. ERROR - Missing Token
POST {{baseUrl}}/blogs
Content-Type: application/json

{
  "title": "Hacker Post",
  "content": "Trying to bypass the auth middleware."
}


### ==========================================
### 🔵 GROUP 3: GET BLOGS (Public)
### ==========================================

### 6. SUCCESS - Get all blogs (Default)
GET {{baseUrl}}/blogs

### 7. SUCCESS - Test Pagination (Page 1, 2 items max)
GET {{baseUrl}}/blogs?page=1&limit=2

### 8. SUCCESS - Test Search (Looks for "API" in title/content)
GET {{baseUrl}}/blogs?search=API

### 9. SUCCESS - Get single blog by ID
GET {{baseUrl}}/blogs/{{blogId}}


### ==========================================
### 🟡 GROUP 4: UPDATE BLOGS
### ==========================================

### 10. SUCCESS - Update blog with valid data
PUT {{baseUrl}}/blogs/{{blogId}}
Authorization:Bearer {{token}}
Content-Type: application/json 

{
  "title": "Updated API Blueprint",
  "content": "I've updated the content of my blog post.",
}
###GROUP 5: DELETE BLOGS
### 11. SUCCESS - Delete a blog
DELETE {{baseUrl}}/blogs/{{blogId}}
Authorization: Bearer {{token}}
#### 12. ERROR - VERIFY DELETION(SHOOULD RETURN 404)
GET {{baseUrl}}/blogs/{{blogId}}